-- =============================================================================
-- DDLs ESENCIALES - Solo las 4 tablas que necesita el Stored Procedure
-- Ejecutar ANTES de correr sp_faco_etl_para_looker_studio
-- =============================================================================

-- Tabla 1: UNIVERSO DE ASIGNACIÓN
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE `mibot-222814.BI_USA.faco_dash_asignacion_universo`
(
  FECHA_ASIGNACION DATE NOT NULL,
  CARTERA STRING NOT NULL,
  SERVICIO STRING NOT NULL,
  SEGMENTO_GESTION STRING NOT NULL,
  VENCIMIENTO DATE,
  ID_ARCHIVO_ASIGNACION STRING NOT NULL,
  ZONA_GEOGRAFICA STRING,
  TIPO_FRACCIONAMIENTO STRING,
  OBJ_RECUPERO FLOAT64,
  Q_CUENTAS_ASIGNADAS INT64,
  Q_CLIENTES_ASIGNADOS INT64,
  MONTO_EXIGIBLE_ASIGNADO FLOAT64,
  DIAS_GESTION_DISPONIBLES FLOAT64
)
PARTITION BY FECHA_ASIGNACION
CLUSTER BY CARTERA, SERVICIO, SEGMENTO_GESTION;

-- Tabla 2: GESTIÓN DIARIA AGREGADA
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE `mibot-222814.BI_USA.faco_dash_gestion_agregada`
(
  FECHA_SERVICIO DATE NOT NULL,
  CARTERA STRING NOT NULL,
  CANAL STRING NOT NULL,
  OPERADOR_FINAL STRING,
  GRUPO_RESPUESTA STRING,
  NIVEL_1 STRING,
  NIVEL_2 STRING,
  SERVICIO STRING,
  SEGMENTO_GESTION STRING,
  ZONA_GEOGRAFICA STRING,
  Q_INTERACCIONES_TOTAL INT64,
  Q_CONTACTOS_EFECTIVOS INT64,
  Q_PROMESAS_DE_PAGO INT64,
  MONTO_COMPROMETIDO FLOAT64,
  Q_CLIENTES_UNICOS_CONTACTADOS INT64,
  Q_CLIENTES_PRIMERA_VEZ_DIA INT64,
  Q_CLIENTES_CON_PROMESA INT64,
  EFECTIVIDAD_CONTACTO FLOAT64,
  TASA_COMPROMISO FLOAT64,
  MONTO_PROMEDIO_COMPROMISO FLOAT64
)
PARTITION BY FECHA_SERVICIO
CLUSTER BY CARTERA, CANAL, OPERADOR_FINAL;

-- Tabla 3: RECUPERO ATRIBUIDO
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE `mibot-222814.BI_USA.faco_dash_recupero_atribuido`
(
  FECHA_PAGO DATE NOT NULL,
  CARTERA STRING NOT NULL,
  SERVICIO STRING,
  ID_ARCHIVO_ASIGNACION STRING,
  CANAL_ATRIBUIDO STRING,
  OPERADOR_ATRIBUIDO STRING,
  FECHA_GESTION_ATRIBUIDA DATE,
  FECHA_COMPROMISO DATE,
  MONTO_PAGADO FLOAT64,
  ES_PAGO_CON_PDP BOOLEAN,
  PDP_ESTABA_VIGENTE BOOLEAN,
  PAGO_ES_PUNTUAL BOOLEAN,
  DIAS_ENTRE_GESTION_Y_PAGO INT64,
  EFECTIVIDAD_ATRIBUCION FLOAT64
)
PARTITION BY FECHA_PAGO
CLUSTER BY CARTERA, CANAL_ATRIBUIDO, OPERADOR_ATRIBUIDO;

-- Tabla 4: KPIS EJECUTIVOS
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE `mibot-222814.BI_USA.faco_dash_kpis_ejecutivos`
(
  FECHA_CALCULO DATE NOT NULL,
  CARTERA STRING NOT NULL,
  SERVICIO STRING,
  CANAL STRING,
  UNIVERSO_CUENTAS INT64,
  UNIVERSO_MONTO FLOAT64,
  OBJ_RECUPERO_PROMEDIO FLOAT64,
  CUENTAS_CONTACTADAS INT64,
  TASA_CONTACTABILIDAD FLOAT64,
  EFECTIVIDAD_PROMEDIO FLOAT64,
  MONTO_COMPROMETIDO FLOAT64,
  TASA_COMPROMISO_PROMEDIO FLOAT64,
  MONTO_RECUPERADO FLOAT64,
  TASA_RECUPERACION FLOAT64,
  CUMPLIMIENTO_OBJETIVO FLOAT64
)
PARTITION BY FECHA_CALCULO
CLUSTER BY CARTERA, SERVICIO, CANAL;

-- =============================================================================
-- VERIFICACIÓN: Confirmar que las tablas se crearon correctamente
-- =============================================================================
SELECT 
  table_name,
  creation_time,
  row_count
FROM `mibot-222814.BI_USA.__TABLES__` 
WHERE table_id LIKE 'faco_dash_%'
ORDER BY table_name;